### PR TITLE
Feat/morsecode

### PR DESCRIPTION
**Pull request by SabiMantock**
main features:
- Create a method to decode a Morse code character, takes a string parameter, and return the corresponding character in uppercase returning "A".
- Create a method to decode an entire word in Morse code, takes a string parameter, and return the string representation. A single space will separate every character in a word return "MY"
- Create a method to decode the message in Morse code, take a string parameter, and return the string representation. 3 spaces will separate every word

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @SabiMantock, @Outkarm and @lawrahkonwea, Kindly add the future features section in your readme 👍🏿

**Comment by SabiMantock** [comment]
Hello @prolajumokeoni ,
I hope this message finds you well. I wanted to inquire about the feedback you provided on my project. You marked it as invalid due to future features. Would you kindly clarify what specific features you are referring to? My understanding of future features is that they are additional functionalities that will be added in the future. If there are no such features planned, perhaps you could consider indicating "N/A" in that section to inform the reviewer that no future features are expected. Thank you for your time and assistance.

**Comment by prolajumokeoni** [comment]
Hi @Team, kindly note that having content in all sections of your readme is a requirement to get a review, please think about future features that can make your code better in future 👍🏿

**Review by EricMbouwe — APPROVED** [review]
Hi @SabiMantock,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🔥
- Has #decode_char method ⚡
- Has `#decode_word` method and works as expected ⚡
- Has `#decode` method and works as expected ⚡
- Expected results ⚡

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
